# Generated by Django 4.2 on 2023-04-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.usermodel')),
            ],
            bases=('user.usermodel',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, unique=True)),
                ('item_detail', models.TextField(max_length=200)),
                ('discount', models.CharField(choices=[('40', '40'), ('30', '30'), ('20', '20'), ('10', '10'), ('No', 'No')], max_length=10)),
                ('comment', models.TextField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.catproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
