# Generated by Django 4.2 on 2023-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='@mail')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('customer', models.BooleanField(default=False)),
            ],
        ),
    ]
